#VARIABLE = A container for a value (String , integer , float , boolean)
#  a variable behaves as if it was the value it contains


#strings
first_name = 'vedik'
food = "pizza"
print(f"the first name is {first_name} and he likes to eat {food}")

#integers
age =25
quantity =3
print(f"the average of the developers in this company is{age} ")
print(f" the quantity of token required is {quantity}")

#float
price = 10.99
gpa =3.4

#boolean/True/False
isEmpty = True
print(f"if the water tank is full? : {isEmpty}")
if isEmpty != False :
    print(f"the water tank is full")
else:
    print(f"the water tank is empty")
